name: Build Apptainer Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup
          wget https://github.com/apptainer/apptainer/releases/download/v1.3.1/apptainer_1.3.1_amd64.deb
          sudo dpkg -i apptainer_1.3.1_amd64.deb

      - name: Build .sif helloworld
        run: |
          apptainer build helloworld.sif Singularity

      - name: Upload .sif as artifact
        uses: actions/upload-artifact@v4
        with:
          name: apptainer-image
          path: helloworld.sif
